// src/shared/components/CommandPalette.svelte
<script lang="ts">
  import { onMount, onDestroy, tick } from "svelte";
  import { navigate } from "@/lib/router";
  import {
    commandPaletteOpen,
    setCommandPaletteOpen,
    theme,
    setTheme,
    sidebarOpen,
    toggleSidebar,
  } from "@/shared/store/ui-store";
  import { documents } from "@/features/documents/store/document-store";
  import { activeWorkspaceId } from "@/features/workspace/store/workspace-store";
  import * as db from "@/lib/tauri/database";
  import {
    FileText,
    Plus,
    Upload,
    Settings,
    Sun,
    Moon,
    Monitor,
    PanelLeftClose,
    PanelLeftOpen,
    Search,
  } from "lucide-svelte";

  let query = "";
  let selectedIndex = 0;
  let inputRef: HTMLInputElement;

  // All available items
  interface CommandItem {
    id: string;
    label: string;
    group: string;
    icon: typeof FileText;
    value: string;
  }

  $: actionItems = [
    { id: "new-doc", label: "New Document", group: "Actions", icon: Plus, value: "new-doc" },
    { id: "settings", label: "Open Settings", group: "Actions", icon: Settings, value: "settings" },
    { id: "projects", label: "View Projects", group: "Actions", icon: Upload, value: "projects" },
    { id: "toggle-sidebar", label: "Toggle Sidebar", group: "Actions", icon: $sidebarOpen ? PanelLeftClose : PanelLeftOpen, value: "toggle-sidebar" },
  ] as CommandItem[];

  $: themeItems = [
    { id: "theme-light", label: "Light Theme", group: "Theme", icon: Sun, value: "theme-light" },
    { id: "theme-dark", label: "Dark Theme", group: "Theme", icon: Moon, value: "theme-dark" },
    { id: "theme-system", label: "System Theme", group: "Theme", icon: Monitor, value: "theme-system" },
  ] as CommandItem[];

  $: docItems = $documents.map((doc) => ({
    id: `doc:${doc.id}`,
    label: doc.title,
    group: "Documents",
    icon: FileText,
    value: `doc:${doc.id}`,
  })) as CommandItem[];

  $: allItems = [...docItems, ...actionItems, ...themeItems];

  $: filteredItems = query.trim()
    ? allItems.filter((item) =>
        item.label.toLowerCase().includes(query.toLowerCase())
      )
    : allItems;

  $: groups = filteredItems.reduce<Record<string, CommandItem[]>>((acc, item) => {
    if (!acc[item.group]) acc[item.group] = [];
    acc[item.group].push(item);
    return acc;
  }, {});

  $: groupOrder = ["Documents", "Actions", "Theme"].filter((g) => groups[g]);

  // Reset selectedIndex when filtered items change
  $: if (filteredItems) {
    selectedIndex = 0;
  }

  function handleSelect(value: string) {
    setCommandPaletteOpen(false);
    query = "";

    if (value.startsWith("doc:")) {
      navigate(`/workspace/${value.replace("doc:", "")}`);
    } else if (value === "new-doc") {
      if ($activeWorkspaceId) {
        const id = crypto.randomUUID();
        db.createDocument(id, $activeWorkspaceId, "Untitled").then(() => {
          navigate(`/workspace/${id}`);
        });
      }
    } else if (value === "settings") {
      navigate("/settings");
    } else if (value === "projects") {
      navigate("/projects");
    } else if (value === "theme-light") {
      setTheme("light");
    } else if (value === "theme-dark") {
      setTheme("dark");
    } else if (value === "theme-system") {
      setTheme("system");
    } else if (value === "toggle-sidebar") {
      toggleSidebar();
    }
  }

  function handleKeydown(e: KeyboardEvent) {
    if (e.key === "k" && (e.metaKey || e.ctrlKey)) {
      e.preventDefault();
      setCommandPaletteOpen(!$commandPaletteOpen);
      return;
    }

    if (!$commandPaletteOpen) return;

    if (e.key === "Escape") {
      setCommandPaletteOpen(false);
      query = "";
      return;
    }

    if (e.key === "ArrowDown") {
      e.preventDefault();
      selectedIndex = (selectedIndex + 1) % filteredItems.length;
    } else if (e.key === "ArrowUp") {
      e.preventDefault();
      selectedIndex = (selectedIndex - 1 + filteredItems.length) % filteredItems.length;
    } else if (e.key === "Enter") {
      e.preventDefault();
      if (filteredItems[selectedIndex]) {
        handleSelect(filteredItems[selectedIndex].value);
      }
    }
  }

  // Focus input when palette opens
  $: if ($commandPaletteOpen) {
    tick().then(() => {
      inputRef?.focus();
    });
  }

  onMount(() => {
    document.addEventListener("keydown", handleKeydown);
  });

  onDestroy(() => {
    document.removeEventListener("keydown", handleKeydown);
  });
</script>

{#if $commandPaletteOpen}
  <div class="fixed inset-0 z-50 flex items-start justify-center pt-[20vh]">
    <!-- Backdrop -->
    <div
      class="fixed inset-0 bg-black/50"
      on:click={() => { setCommandPaletteOpen(false); query = ""; }}
      on:keydown={(e) => e.key === "Escape" && setCommandPaletteOpen(false)}
      role="button"
      tabindex="-1"
    />

    <!-- Palette -->
    <div class="relative w-full max-w-lg rounded-xl border border-border bg-popover shadow-2xl">
      <div class="flex items-center gap-2 border-b border-border px-3">
        <Search class="h-4 w-4 text-muted-foreground" />
        <input
          bind:this={inputRef}
          bind:value={query}
          class="flex-1 bg-transparent py-3 text-sm outline-none placeholder:text-muted-foreground"
          placeholder="Search documents, actions..."
        />
      </div>
      <div class="max-h-80 overflow-auto p-2">
        {#if filteredItems.length === 0}
          <div class="px-4 py-8 text-center text-sm text-muted-foreground">
            No results found.
          </div>
        {:else}
          {#each groupOrder as groupName}
            <div class="mb-1">
              <div class="px-2 py-1.5 text-xs font-medium text-muted-foreground">
                {groupName}
              </div>
              {#each groups[groupName] as item, i}
                {@const globalIndex = filteredItems.indexOf(item)}
                <button
                  class="flex w-full cursor-pointer items-center gap-2 rounded-md px-2 py-1.5 text-sm {globalIndex === selectedIndex ? 'bg-accent' : ''}"
                  on:click={() => handleSelect(item.value)}
                  on:mouseenter={() => (selectedIndex = globalIndex)}
                >
                  <svelte:component this={item.icon} class="h-4 w-4 text-muted-foreground" />
                  {item.label}
                </button>
              {/each}
            </div>
          {/each}
        {/if}
      </div>
    </div>
  </div>
{/if}

// src/shared/components/CommandPalette.tsx
import { useEffect, useCallback } from "react";
import { Command } from "cmdk";
import { useNavigate } from "react-router-dom";
import { useUIStore } from "@/shared/store/ui-store";
import { useDocumentStore } from "@/features/documents/store/document-store";
import { useWorkspaceStore } from "@/features/workspace/store/workspace-store";
import * as db from "@/lib/tauri/database";
import {
  FileText,
  Plus,
  Upload,
  Settings,
  Sun,
  Moon,
  Monitor,
  PanelLeftClose,
  PanelLeftOpen,
  Search,
} from "lucide-react";

export function CommandPalette() {
  const open = useUIStore((s) => s.commandPaletteOpen);
  const setOpen = useUIStore((s) => s.setCommandPaletteOpen);
  const theme = useUIStore((s) => s.theme);
  const setTheme = useUIStore((s) => s.setTheme);
  const sidebarOpen = useUIStore((s) => s.sidebarOpen);
  const toggleSidebar = useUIStore((s) => s.toggleSidebar);
  const documents = useDocumentStore((s) => s.documents);
  const activeWorkspaceId = useWorkspaceStore((s) => s.activeWorkspaceId);
  const navigate = useNavigate();

  // Cmd+K to toggle
  useEffect(() => {
    const down = (e: KeyboardEvent) => {
      if (e.key === "k" && (e.metaKey || e.ctrlKey)) {
        e.preventDefault();
        setOpen(!open);
      }
    };
    document.addEventListener("keydown", down);
    return () => document.removeEventListener("keydown", down);
  }, [open, setOpen]);

  const handleSelect = useCallback(
    (value: string) => {
      setOpen(false);

      if (value.startsWith("doc:")) {
        navigate(`/workspace/${value.replace("doc:", "")}`);
      } else if (value === "new-doc") {
        if (activeWorkspaceId) {
          const id = crypto.randomUUID();
          db.createDocument(id, activeWorkspaceId, "Untitled").then(() => {
            navigate(`/workspace/${id}`);
          });
        }
      } else if (value === "settings") {
        navigate("/settings");
      } else if (value === "projects") {
        navigate("/projects");
      } else if (value === "theme-light") {
        setTheme("light");
      } else if (value === "theme-dark") {
        setTheme("dark");
      } else if (value === "theme-system") {
        setTheme("system");
      } else if (value === "toggle-sidebar") {
        toggleSidebar();
      }
    },
    [navigate, setOpen, activeWorkspaceId, setTheme, toggleSidebar]
  );

  if (!open) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-start justify-center pt-[20vh]">
      <div
        className="fixed inset-0 bg-black/50"
        onClick={() => setOpen(false)}
      />
      <Command
        className="relative w-full max-w-lg rounded-xl border border-border bg-popover shadow-2xl"
        onKeyDown={(e: React.KeyboardEvent) => {
          if (e.key === "Escape") setOpen(false);
        }}
      >
        <div className="flex items-center gap-2 border-b border-border px-3">
          <Search className="h-4 w-4 text-muted-foreground" />
          <Command.Input
            className="flex-1 bg-transparent py-3 text-sm outline-none placeholder:text-muted-foreground"
            placeholder="Search documents, actions..."
            autoFocus
          />
        </div>
        <Command.List className="max-h-80 overflow-auto p-2">
          <Command.Empty className="px-4 py-8 text-center text-sm text-muted-foreground">
            No results found.
          </Command.Empty>

          {documents.length > 0 && (
            <Command.Group heading="Documents" className="[&_[cmdk-group-heading]]:px-2 [&_[cmdk-group-heading]]:py-1.5 [&_[cmdk-group-heading]]:text-xs [&_[cmdk-group-heading]]:font-medium [&_[cmdk-group-heading]]:text-muted-foreground">
              {documents.map((doc) => (
                <Command.Item
                  key={doc.id}
                  value={`doc:${doc.id}`}
                  onSelect={handleSelect}
                  className="flex cursor-pointer items-center gap-2 rounded-md px-2 py-1.5 text-sm aria-selected:bg-accent"
                >
                  <FileText className="h-4 w-4 text-muted-foreground" />
                  {doc.title}
                </Command.Item>
              ))}
            </Command.Group>
          )}

          <Command.Group heading="Actions" className="[&_[cmdk-group-heading]]:px-2 [&_[cmdk-group-heading]]:py-1.5 [&_[cmdk-group-heading]]:text-xs [&_[cmdk-group-heading]]:font-medium [&_[cmdk-group-heading]]:text-muted-foreground">
            <Command.Item
              value="new-doc"
              onSelect={handleSelect}
              className="flex cursor-pointer items-center gap-2 rounded-md px-2 py-1.5 text-sm aria-selected:bg-accent"
            >
              <Plus className="h-4 w-4 text-muted-foreground" />
              New Document
            </Command.Item>
            <Command.Item
              value="settings"
              onSelect={handleSelect}
              className="flex cursor-pointer items-center gap-2 rounded-md px-2 py-1.5 text-sm aria-selected:bg-accent"
            >
              <Settings className="h-4 w-4 text-muted-foreground" />
              Open Settings
            </Command.Item>
            <Command.Item
              value="projects"
              onSelect={handleSelect}
              className="flex cursor-pointer items-center gap-2 rounded-md px-2 py-1.5 text-sm aria-selected:bg-accent"
            >
              <Upload className="h-4 w-4 text-muted-foreground" />
              View Projects
            </Command.Item>
            <Command.Item
              value="toggle-sidebar"
              onSelect={handleSelect}
              className="flex cursor-pointer items-center gap-2 rounded-md px-2 py-1.5 text-sm aria-selected:bg-accent"
            >
              {sidebarOpen ? (
                <PanelLeftClose className="h-4 w-4 text-muted-foreground" />
              ) : (
                <PanelLeftOpen className="h-4 w-4 text-muted-foreground" />
              )}
              Toggle Sidebar
            </Command.Item>
          </Command.Group>

          <Command.Group heading="Theme" className="[&_[cmdk-group-heading]]:px-2 [&_[cmdk-group-heading]]:py-1.5 [&_[cmdk-group-heading]]:text-xs [&_[cmdk-group-heading]]:font-medium [&_[cmdk-group-heading]]:text-muted-foreground">
            <Command.Item
              value="theme-light"
              onSelect={handleSelect}
              className="flex cursor-pointer items-center gap-2 rounded-md px-2 py-1.5 text-sm aria-selected:bg-accent"
            >
              <Sun className="h-4 w-4 text-muted-foreground" />
              Light Theme
            </Command.Item>
            <Command.Item
              value="theme-dark"
              onSelect={handleSelect}
              className="flex cursor-pointer items-center gap-2 rounded-md px-2 py-1.5 text-sm aria-selected:bg-accent"
            >
              <Moon className="h-4 w-4 text-muted-foreground" />
              Dark Theme
            </Command.Item>
            <Command.Item
              value="theme-system"
              onSelect={handleSelect}
              className="flex cursor-pointer items-center gap-2 rounded-md px-2 py-1.5 text-sm aria-selected:bg-accent"
            >
              <Monitor className="h-4 w-4 text-muted-foreground" />
              System Theme
            </Command.Item>
          </Command.Group>
        </Command.List>
      </Command>
    </div>
  );
}
