// src/layouts/AppLayout.svelte
<script lang="ts">
  import { onMount, onDestroy } from "svelte";
  import { sidebarOpen } from "@/shared/store/ui-store";
  import { setupKeyboardShortcuts } from "@/shared/hooks/keyboard-shortcuts";
  import ActivityBar from "./ActivityBar.svelte";
  import Sidebar from "./Sidebar.svelte";
  import Router from "@/lib/Router.svelte";
  import PublishPanel from "@/features/publishing/components/PublishPanel.svelte";
  import CommandPalette from "@/shared/components/CommandPalette.svelte";

  let publishPanelOpen = false;
  let cleanupShortcuts: (() => void) | undefined;

  onMount(() => {
    cleanupShortcuts = setupKeyboardShortcuts();

    const handler = () => { publishPanelOpen = true; };
    window.addEventListener("specra:open-publish", handler);
    return () => window.removeEventListener("specra:open-publish", handler);
  });

  onDestroy(() => cleanupShortcuts?.());
</script>

<div class="flex h-screen w-screen overflow-hidden bg-background">
  <ActivityBar onPublish={() => { publishPanelOpen = true; }} />
  {#if $sidebarOpen}
    <Sidebar />
  {/if}
  <main class="flex-1 overflow-auto">
    <Router />
  </main>
  {#if publishPanelOpen}
    <PublishPanel onClose={() => { publishPanelOpen = false; }} />
  {/if}
  <CommandPalette />
</div>

// src/layouts/AppLayout.tsx
import { useState, useEffect } from "react";
import { Outlet } from "react-router-dom";
import { ActivityBar } from "./ActivityBar";
import { Sidebar } from "./Sidebar";
import { useUIStore } from "@/shared/store/ui-store";
import { PublishPanel } from "@/features/publishing/components/PublishPanel";
import { CommandPalette } from "@/shared/components/CommandPalette";
import { useKeyboardShortcuts } from "@/shared/hooks/useKeyboardShortcuts";

export function AppLayout() {
  const sidebarOpen = useUIStore((s) => s.sidebarOpen);
  const [publishPanelOpen, setPublishPanelOpen] = useState(false);

  useKeyboardShortcuts();

  // Listen for Cmd+P publish shortcut
  useEffect(() => {
    const handler = () => setPublishPanelOpen(true);
    window.addEventListener("specra:open-publish", handler);
    return () => window.removeEventListener("specra:open-publish", handler);
  }, []);

  return (
    <div className="flex h-screen w-screen overflow-hidden bg-background">
      <ActivityBar onPublish={() => setPublishPanelOpen(true)} />
      {sidebarOpen && <Sidebar />}
      <main className="flex-1 overflow-auto">
        <Outlet />
      </main>
      {publishPanelOpen && (
        <PublishPanel onClose={() => setPublishPanelOpen(false)} />
      )}
      <CommandPalette />
    </div>
  );
}
